name: veinmind-weakpass
on: [push]
jobs:
  build-amd64-static:
    runs-on: ubuntu-18.04
    env:
      CI_GOOS: linux
      CI_GOARCH: amd64
      TAGS: "community,static"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.1'
      - run: /bin/bash scripts/libveinmind/install_libveinmind_debian.sh
      - run: cd veinmind-weakpass && /bin/bash -x ../scripts/build/build_veinmind_weakpass_amd64.sh
      - uses: actions/upload-artifact@v2
        with:
          name: veinmind-weakpass-amd64
          path: ./veinmind-weakpass/artifacts/${{env.CI_GOOS}}-${{env.CI_GOARCH}}/veinmind-weakpass_${{env.CI_GOOS}}_${{env.CI_GOARCH}}
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./veinmind-weakpass/artifacts/${{env.CI_GOOS}}-${{env.CI_GOARCH}}/veinmind-weakpass_${{env.CI_GOOS}}_${{env.CI_GOARCH}}
  build-amd64-dynamic:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-18.04
    container:
      image: veinmind/go1.16:1.0.4-stretch
    env:
      CI_GOOS: linux
      CI_GOARCH: amd64
      TAGS: "community,dynamic"
    steps:
      - uses: actions/checkout@v2
      - run: cd veinmind-weakpass && /bin/bash -x ../scripts/build/build_veinmind_weakpass_amd64.sh
      - uses: actions/upload-artifact@v2
        with:
          name: veinmind-weakpass-amd64-dynamic
          path: ./veinmind-weakpass/artifacts/${{env.CI_GOOS}}-${{env.CI_GOARCH}}/veinmind-weakpass_${{env.CI_GOOS}}_${{env.CI_GOARCH}}
  push-amd64-image:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build-amd64-dynamic
    runs-on: ubuntu-18.04
    env:
      CI_GOOS: linux
      CI_GOARCH: amd64
    steps:
      - uses: actions/checkout@v2
      - run: cp -r ./veinmind-common ./veinmind-weakpass && rm -rf ./veinmind-weakpass/veinmind-common/python
      - uses: actions/download-artifact@v2
        with:
          name: veinmind-weakpass-amd64-dynamic
      - run: mv veinmind-weakpass_${{env.CI_GOOS}}_${{env.CI_GOARCH}} ./veinmind-weakpass
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            veinmind/veinmind-weakpass:latest
            veinmind/veinmind-weakpass:${{github.ref_name}}
          context: ./veinmind-weakpass
          build-args: |
            CI_GOOS=${{env.CI_GOOS}}
            CI_GOARCH=${{env.CI_GOARCH}}